apiVersion: v1
data:
  filebeat.yml: |-
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
      inputs:
        path: ${path.config}/inputs.d/*.yml
        reload.enabled: false
 
    processors:
      - add_cloud_metadata:

    fields:
      kubernetes_cluster: my-cluster
      env: development
 
    setup:
      template:
        #name: "<CLUSTER_NAME>-%{[beat.version]}"
        name: "filebeat-%{[beat.version]}"
        #pattern: "<CLUSTER_NAME>-*"
        pattern: "filebeat-*"
      dashboards:
        #index: "<CLUSTER_NAME>-*"
        index: "filebeat-*"
      kibana:
        #hosts: https://kibana.domain.com
        host: http://kibana:5601
      #settings:
      #  index.number_of_shards: 1
      #  index.codec: best_compression

    output.elasticsearch:
      #hosts: ["https://elastic.domain.com"]
      hosts: ["https://elasticsearch:9200"]
      username: "test"
      password: "test"
      #index: "<CLUSTER_NAME>-%{[beat.version]}-%{+yyyy.MM}"
      index: "filebeat-%{[beat.version]}-%{+yyyy.MM}"   
kind: ConfigMap
metadata:
  labels:
    app: filebeat
  name: filebeat-config
  namespace: efk-log
---
apiVersion: v1
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      ignore_older: 72h
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
kind: ConfigMap
metadata:
  labels:
    app: filebeat
  name: filebeat-inputs
  namespace: efk-log
---
#   apiVersion: v1
#   kind: ConfigMap
#   metadata:
#     name: ilm-policy
#     labels: 
#       app: filebeat
#   data:
#     ilm-policy.json: |-
#       {
#         "policy": {
#           "phases": {
#             "hot": {
#               "actions": {
#                 "rollover": {
#                   "max_size": "5GB" ,
#                   "max_age": "1d"
#                 },
#                 "set_priority": {
#                   "priority": "100"
#                 }
#               }
#             },
#             "warm": {
#               "min_age": "7d",
#               "action": {
#                 "set_priority": {
#                   "priority": 50
#                 },
#                 "readonly": {}
#               }
#             },
#             "cold": {
#               "min_age": "30d",
#               "action": {
#                 "set_priority": {
#                   "priority": 50
#                 },
#                 "freeze": {}
#               }
#             },
#             "delete": {
#               "min_age": "60d",
#               "actions": {
#                 "delete": {}
#               }
#             }
#           }
#         }
#       }
# ---